// Real India data service with comprehensive resources
export const indiaData = {
  emergencyHelplines: {
    national: [
      {
        name: "Police Emergency",
        number: "100",
        category: "emergency",
        available: "24/7",
        description: "For immediate danger and emergencies",
      },
      {
        name: "National Women Helpline",
        number: "1090",
        category: "women-safety",
        available: "24/7",
        description: "Toll-free support for women in distress",
      },
      {
        name: "Women Helpline (AASRA)",
        number: "9820466726",
        category: "women-support",
        available: "24/7",
        description: "Crisis intervention and counseling",
      },
      {
        name: "iCall Crisis Line",
        number: "9152987821",
        category: "mental-health",
        available: "24/7",
        description: "Mental health and emotional support",
      },
      {
        name: "Vandrevala Foundation",
        number: "9999666555",
        category: "mental-health",
        available: "24/7",
        description: "Crisis counseling and suicide prevention",
      },
      {
        name: "Anti-Human Trafficking",
        number: "1800111555",
        category: "trafficking",
        available: "24/7",
        description: "National human trafficking awareness",
      },
      {
        name: "POCSO Helpline",
        number: "9555000777",
        category: "child-protection",
        available: "24/7",
        description: "Child sexual abuse and exploitation",
      },
      {
        name: "Cyber Crime Helpline",
        number: "1930",
        category: "cybercrime",
        available: "24/7",
        description: "Online harassment and cyber fraud",
      },
      {
        name: "Sexual Harassment at Work",
        number: "1909",
        category: "workplace",
        available: "24/7",
        description: "Workplace sexual harassment complaints",
      },
    ],
    cityWise: {
      delhi: [
        {
          name: "Delhi Women Helpline",
          number: "1091",
          type: "state",
          city: "Delhi",
        },
        {
          name: "Delhi Women Helpline (Alt)",
          number: "011-4141-7343",
          type: "state",
          city: "Delhi",
        },
        {
          name: "Delhi Police - Women Cell",
          number: "011-2330-3999",
          type: "police",
          city: "Delhi",
        },
      ],
      mumbai: [
        {
          name: "Mumbai Women Helpline",
          number: "1090",
          type: "state",
          city: "Mumbai",
        },
        {
          name: "Aasra Helpline",
          number: "9820466726",
          type: "ngo",
          city: "Mumbai",
        },
        {
          name: "Mumbai Police Women Cell",
          number: "22-6169-4438",
          type: "police",
          city: "Mumbai",
        },
      ],
      bangalore: [
        {
          name: "Bangalore Women Helpline",
          number: "1090",
          type: "state",
          city: "Bangalore",
        },
        {
          name: "Bangalore Police Women Cell",
          number: "080-2255-2999",
          type: "police",
          city: "Bangalore",
        },
        {
          name: "Cyber Crime Cell",
          number: "080-4945-6886",
          type: "police",
          city: "Bangalore",
        },
      ],
      kolkata: [
        {
          name: "Kolkata Women Helpline",
          number: "1090",
          type: "state",
          city: "Kolkata",
        },
        {
          name: "Kolkata Police Women Cell",
          number: "033-4040-2000",
          type: "police",
          city: "Kolkata",
        },
      ],
      pune: [
        {
          name: "Pune Women Helpline",
          number: "1090",
          type: "state",
          city: "Pune",
        },
        {
          name: "Pune Police Women Cell",
          number: "020-2622-1313",
          type: "police",
          city: "Pune",
        },
      ],
      hyderabad: [
        {
          name: "Hyderabad Women Helpline",
          number: "1090",
          type: "state",
          city: "Hyderabad",
        },
        {
          name: "Hyderabad Police Women Cell",
          number: "040-2708-5050",
          type: "police",
          city: "Hyderabad",
        },
      ],
      chennai: [
        {
          name: "Chennai Women Helpline",
          number: "1090",
          type: "state",
          city: "Chennai",
        },
        {
          name: "Chennai Police Women Cell",
          number: "044-2459-5050",
          type: "police",
          city: "Chennai",
        },
      ],
    },
  },
  importantLaws: [
    {
      name: "Indian Penal Code 354",
      description: "Outraging the modesty of women",
      punishment: "Imprisonment up to 3 years or fine up to 2000 rupees",
      applicable: "All of India",
    },
    {
      name: "Indian Penal Code 376",
      description: "Sexual assault/Rape",
      punishment: "Minimum 7 years to life imprisonment",
      applicable: "All of India",
    },
    {
      name: "Indian Penal Code 509",
      description: "Insult to the modesty of women",
      punishment: "Up to 3 years imprisonment or fine",
      applicable: "All of India",
    },
    {
      name: "Dowry Prohibition Act (1961)",
      description: "Prohibition of dowry in marriages",
      punishment: "Up to 5 years imprisonment and fine",
      applicable: "All of India",
    },
    {
      name: "Protection of Women from Domestic Violence Act (2005)",
      description: "Protection from abuse and violence at home",
      punishment: "Up to 1 year imprisonment or fine",
      applicable: "All of India",
    },
    {
      name: "Sexual Harassment of Women at Workplace Act (2013)",
      description: "POSH Act - Workplace safety",
      punishment: "Various disciplinary actions and legal penalties",
      applicable: "All workplaces in India",
    },
    {
      name: "POCSO Act (2012)",
      description: "Protection of Children from Sexual Offences",
      punishment: "Rigorous imprisonment up to 7 years",
      applicable: "Protection for children",
    },
    {
      name: "Cybercrime Protection",
      description: "IPC 354D - Stalking, online harassment",
      punishment: "Up to 3 years imprisonment",
      applicable: "All of India",
    },
  ],
  crimeSafetyData: {
    highRiskAreas: [
      { city: "Delhi", area: "South Delhi", riskLevel: "moderate", incidents: 450 },
      { city: "Delhi", area: "North Delhi", riskLevel: "high", incidents: 680 },
      { city: "Mumbai", area: "Central Mumbai", riskLevel: "moderate", incidents: 320 },
      { city: "Bangalore", area: "South Bangalore", riskLevel: "low", incidents: 150 },
      { city: "Kolkata", area: "Central Kolkata", riskLevel: "moderate", incidents: 280 },
    ],
    safeAreas: [
      { city: "Delhi", area: "Gurgaon", safetyScore: 8.5 },
      { city: "Bangalore", area: "Whitefield", safetyScore: 8.8 },
      { city: "Mumbai", area: "Bandra", safetyScore: 7.9 },
      { city: "Pune", area: "Koregaon Park", safetyScore: 8.2 },
      { city: "Hyderabad", area: "Hitech City", safetyScore: 8.7 },
    ],
  },
  mentalHealthResources: [
    {
      name: "NMHP Services",
      description: "National Mental Health Programme",
      type: "Government",
      availability: "Pan-India",
    },
    {
      name: "NIMHANS Bangalore",
      description: "National Institute of Mental Health",
      type: "Government",
      phone: "080-2699-5100",
      availability: "Online counselling available",
    },
    {
      name: "Wysa",
      type: "App",
      description: "AI mental health support and therapy",
      availability: "Paid + Free options",
    },
    {
      name: "Sanvello",
      type: "App",
      description: "Mood tracking and therapy support",
      availability: "Paid + Free trial",
    },
    {
      name: "BetterHelp",
      type: "Online",
      description: "Online therapy with licensed therapists",
      availability: "Paid (accepts Indian therapists)",
    },
  ],
  selfDefenseResources: [
    {
      name: "Women's Self Defense Classes",
      description: "Martial arts training in major cities",
      cities: ["Delhi", "Mumbai", "Bangalore", "Pune", "Hyderabad"],
    },
    {
      name: "Pepper Spray",
      description: "Legal self-defense tool (with permit)",
      availability: "Online and retail stores",
      legalInIndia: true,
    },
    {
      name: "Personal Safety Apps",
      tools: [
        { name: "bSafe", description: "Emergency alert and location sharing" },
        { name: "Circle of 6", description: "Friends support system" },
        { name: "TravelSafe", description: "Travel safety monitoring" },
        { name: "SafetiPin", description: "Safety rating and resources" },
      ],
    },
  ],
}

export const cityLocations = {
  Delhi: [
    { name: "India Gate", lat: 28.6129, lng: 77.2295, type: "landmark", category: "Public Place" },
    { name: "Connaught Place", lat: 28.6305, lng: 77.1896, type: "landmark", category: "Shopping" },
    { name: "New Delhi Railway Station", lat: 28.6431, lng: 77.2197, type: "transport", category: "Transport Hub" },
    { name: "Delhi International Airport", lat: 28.556, lng: 77.1033, type: "transport", category: "Transport Hub" },
    { name: "Indira Gandhi Memorial", lat: 28.5958, lng: 77.2512, type: "landmark", category: "Public Place" },
    { name: "Lodi Garden", lat: 28.5933, lng: 77.2207, type: "park", category: "Park" },
    { name: "Ram Lila Ground", lat: 28.6475, lng: 77.2436, type: "public", category: "Public Ground" },
    { name: "Delhi Police Station - Central", lat: 28.6295, lng: 77.1896, type: "police", category: "Police Station" },
    { name: "Max Hospital Delhi", lat: 28.6139, lng: 77.209, type: "hospital", category: "Hospital" },
    { name: "AIIMS Delhi", lat: 28.5684, lng: 77.2102, type: "hospital", category: "Hospital" },
  ],
  Mumbai: [
    { name: "Gateway of India", lat: 18.9563, lng: 72.8354, type: "landmark", category: "Public Place" },
    { name: "Marine Drive", lat: 18.9432, lng: 72.8289, type: "landmark", category: "Public Place" },
    { name: "Chhatrapati Shivaji Terminus", lat: 18.9337, lng: 72.8326, type: "transport", category: "Transport Hub" },
    { name: "Mumbai International Airport", lat: 19.0904, lng: 72.8656, type: "transport", category: "Transport Hub" },
    { name: "Linking Road", lat: 19.0197, lng: 72.8277, type: "landmark", category: "Shopping" },
    { name: "Worli Sea Face", lat: 19.0176, lng: 72.8194, type: "park", category: "Park" },
    { name: "Mumbai Police Station - Main", lat: 18.9563, lng: 72.8354, type: "police", category: "Police Station" },
    { name: "Breach Candy Hospital", lat: 19.0263, lng: 72.8316, type: "hospital", category: "Hospital" },
    { name: "St. George Hospital", lat: 18.9537, lng: 72.8299, type: "hospital", category: "Hospital" },
  ],
  Bangalore: [
    { name: "Vidhana Soudha", lat: 12.9795, lng: 77.5903, type: "landmark", category: "Public Place" },
    { name: "Cubbon Park", lat: 12.9716, lng: 77.5946, type: "park", category: "Park" },
    { name: "Brigade Road", lat: 12.9716, lng: 77.5946, type: "landmark", category: "Shopping" },
    {
      name: "Kempegowda International Airport",
      lat: 13.1939,
      lng: 77.7064,
      type: "transport",
      category: "Transport Hub",
    },
    {
      name: "Bangalore City Railway Station",
      lat: 12.9756,
      lng: 77.6411,
      type: "transport",
      category: "Transport Hub",
    },
    { name: "Bangalore Central Police", lat: 12.9716, lng: 77.5946, type: "police", category: "Police Station" },
    { name: "Apollo Hospital Bangalore", lat: 13.0359, lng: 77.6245, type: "hospital", category: "Hospital" },
    { name: "St. Martha's Hospital", lat: 13.0359, lng: 77.5903, type: "hospital", category: "Hospital" },
  ],
  Kolkata: [
    { name: "Victoria Memorial", lat: 22.5448, lng: 88.3426, type: "landmark", category: "Public Place" },
    { name: "Howrah Bridge", lat: 22.5731, lng: 88.3639, type: "landmark", category: "Public Place" },
    { name: "Howrah Railway Station", lat: 22.5898, lng: 88.2775, type: "transport", category: "Transport Hub" },
    {
      name: "Netaji Subhas Chandra Bose International Airport",
      lat: 22.6542,
      lng: 88.4467,
      type: "transport",
      category: "Transport Hub",
    },
    { name: "Kolkata Police - Main Office", lat: 22.5726, lng: 88.3639, type: "police", category: "Police Station" },
    { name: "AMRI Hospital", lat: 22.4885, lng: 88.3763, type: "hospital", category: "Hospital" },
  ],
  Pune: [
    { name: "Aga Khan Palace", lat: 18.5297, lng: 73.8786, type: "landmark", category: "Public Place" },
    { name: "Koregaon Park", lat: 18.5333, lng: 73.8667, type: "park", category: "Park" },
    { name: "Pune Railway Station", lat: 18.5241, lng: 73.8474, type: "transport", category: "Transport Hub" },
    { name: "Pune Airport", lat: 18.5799, lng: 73.9197, type: "transport", category: "Transport Hub" },
    { name: "Pune Police Headquarters", lat: 18.5197, lng: 73.8567, type: "police", category: "Police Station" },
    { name: "Ruby Hall Clinic", lat: 18.5299, lng: 73.9272, type: "hospital", category: "Hospital" },
  ],
  Hyderabad: [
    { name: "Charminar", lat: 17.3607, lng: 78.4594, type: "landmark", category: "Public Place" },
    {
      name: "Hyderabad International Airport",
      lat: 17.3898,
      lng: 78.4389,
      type: "transport",
      category: "Transport Hub",
    },
    { name: "Hyderabad Railway Station", lat: 17.3644, lng: 78.4736, type: "transport", category: "Transport Hub" },
    { name: "Hyderabad Police - Main Office", lat: 17.3833, lng: 78.4784, type: "police", category: "Police Station" },
    { name: "Apollo Hospital Hyderabad", lat: 17.4239, lng: 78.4436, type: "hospital", category: "Hospital" },
  ],
  Chennai: [
    { name: "Marina Beach", lat: 13.0499, lng: 80.2822, type: "landmark", category: "Public Place" },
    {
      name: "Chennai Central Railway Station",
      lat: 13.0847,
      lng: 80.2744,
      type: "transport",
      category: "Transport Hub",
    },
    { name: "Chennai International Airport", lat: 12.9942, lng: 80.1709, type: "transport", category: "Transport Hub" },
    {
      name: "Chennai Police Commissioner Office",
      lat: 13.0827,
      lng: 80.2707,
      type: "police",
      category: "Police Station",
    },
    { name: "Apollo Hospital Chennai", lat: 13.0499, lng: 80.2822, type: "hospital", category: "Hospital" },
  ],
  Gurgaon: [
    { name: "Cyber Hub", lat: 28.4595, lng: 77.0266, type: "landmark", category: "Shopping" },
    { name: "Gurgaon Railway Station", lat: 28.4595, lng: 77.0266, type: "transport", category: "Transport Hub" },
    { name: "Gurgaon Police Headquarters", lat: 28.4595, lng: 77.0266, type: "police", category: "Police Station" },
    { name: "Max Hospital Gurgaon", lat: 28.4595, lng: 77.0266, type: "hospital", category: "Hospital" },
  ],
}

export const criminalAreasData = {
  Delhi: [
    {
      area: "Delhi Central",
      lat: 28.6139,
      lng: 77.209,
      crimeRate: 8.5,
      incidents: 2340,
      types: ["theft", "harassment", "assault"],
      safetyScore: 2.5,
    },
    {
      area: "North Delhi",
      lat: 28.7635,
      lng: 77.2273,
      crimeRate: 9.2,
      incidents: 3120,
      types: ["robbery", "harassment"],
      safetyScore: 1.8,
    },
    {
      area: "South Delhi",
      lat: 28.5485,
      lng: 77.2099,
      crimeRate: 6.5,
      incidents: 1890,
      types: ["theft", "cyber"],
      safetyScore: 5.5,
    },
    {
      area: "East Delhi",
      lat: 28.6074,
      lng: 77.3214,
      crimeRate: 7.8,
      incidents: 2100,
      types: ["harassment", "theft"],
      safetyScore: 3.2,
    },
    {
      area: "West Delhi",
      lat: 28.6392,
      lng: 77.047,
      crimeRate: 7.2,
      incidents: 1950,
      types: ["theft", "assault"],
      safetyScore: 4.1,
    },
    {
      area: "Gurgaon",
      lat: 28.4595,
      lng: 77.0266,
      crimeRate: 5.1,
      incidents: 980,
      types: ["cyber", "theft"],
      safetyScore: 7.2,
    },
    {
      area: "Noida",
      lat: 28.5355,
      lng: 77.391,
      crimeRate: 6.8,
      incidents: 1680,
      types: ["theft", "harassment"],
      safetyScore: 4.8,
    },
  ],
  Mumbai: [
    {
      area: "Central Mumbai",
      lat: 18.9563,
      lng: 72.8354,
      crimeRate: 8.9,
      incidents: 2890,
      types: ["robbery", "harassment"],
      safetyScore: 2.1,
    },
    {
      area: "South Mumbai",
      lat: 18.9432,
      lng: 72.8289,
      crimeRate: 6.2,
      incidents: 1420,
      types: ["theft", "cyber"],
      safetyScore: 6.8,
    },
    {
      area: "North Mumbai",
      lat: 19.1136,
      lng: 72.8697,
      crimeRate: 8.1,
      incidents: 2100,
      types: ["harassment", "theft"],
      safetyScore: 3.9,
    },
    { area: "Bandra", lat: 19.0596, lng: 72.8295, crimeRate: 5.4, incidents: 890, types: ["theft"], safetyScore: 7.1 },
    {
      area: "Andheri",
      lat: 19.1136,
      lng: 72.8697,
      crimeRate: 7.3,
      incidents: 1750,
      types: ["harassment", "assault"],
      safetyScore: 4.2,
    },
    {
      area: "Dadar",
      lat: 19.0176,
      lng: 72.8194,
      crimeRate: 7.8,
      incidents: 1950,
      types: ["theft", "harassment"],
      safetyScore: 3.8,
    },
    {
      area: "Worli",
      lat: 19.0172,
      lng: 72.809,
      crimeRate: 6.1,
      incidents: 1200,
      types: ["cyber", "theft"],
      safetyScore: 6.5,
    },
  ],
  Bangalore: [
    {
      area: "Bangalore Central",
      lat: 12.9716,
      lng: 77.5946,
      crimeRate: 6.8,
      incidents: 1560,
      types: ["theft", "cyber"],
      safetyScore: 5.2,
    },
    {
      area: "South Bangalore",
      lat: 12.912,
      lng: 77.6245,
      crimeRate: 4.2,
      incidents: 680,
      types: ["theft"],
      safetyScore: 8.1,
    },
    {
      area: "North Bangalore",
      lat: 13.0359,
      lng: 77.5903,
      crimeRate: 7.5,
      incidents: 1820,
      types: ["harassment", "theft"],
      safetyScore: 3.5,
    },
    {
      area: "East Bangalore",
      lat: 12.9716,
      lng: 77.6411,
      crimeRate: 6.3,
      incidents: 1340,
      types: ["theft", "harassment"],
      safetyScore: 5.8,
    },
    {
      area: "Whitefield",
      lat: 12.9698,
      lng: 77.7499,
      crimeRate: 3.8,
      incidents: 520,
      types: ["cyber"],
      safetyScore: 8.9,
    },
    {
      area: "Indiranagar",
      lat: 12.9716,
      lng: 77.6441,
      crimeRate: 5.2,
      incidents: 890,
      types: ["theft"],
      safetyScore: 7.2,
    },
    {
      area: "Koramangala",
      lat: 12.9352,
      lng: 77.6245,
      crimeRate: 6.9,
      incidents: 1650,
      types: ["harassment", "theft"],
      safetyScore: 4.9,
    },
  ],
  Kolkata: [
    {
      area: "Kolkata Central",
      lat: 22.5726,
      lng: 88.3639,
      crimeRate: 7.8,
      incidents: 1890,
      types: ["theft", "harassment"],
      safetyScore: 3.9,
    },
    {
      area: "South Kolkata",
      lat: 22.4885,
      lng: 88.3763,
      crimeRate: 5.4,
      incidents: 950,
      types: ["theft"],
      safetyScore: 7.0,
    },
    {
      area: "North Kolkata",
      lat: 22.6442,
      lng: 88.3678,
      crimeRate: 8.2,
      incidents: 2150,
      types: ["robbery", "harassment"],
      safetyScore: 2.8,
    },
    {
      area: "East Kolkata",
      lat: 22.5719,
      lng: 88.4284,
      crimeRate: 6.8,
      incidents: 1420,
      types: ["harassment", "theft"],
      safetyScore: 4.7,
    },
    {
      area: "Salt Lake",
      lat: 22.5478,
      lng: 88.4282,
      crimeRate: 3.9,
      incidents: 520,
      types: ["cyber"],
      safetyScore: 8.5,
    },
  ],
  Pune: [
    {
      area: "Pune Central",
      lat: 18.5204,
      lng: 73.8567,
      crimeRate: 6.5,
      incidents: 1240,
      types: ["theft", "cyber"],
      safetyScore: 5.3,
    },
    {
      area: "Koregaon Park",
      lat: 18.5297,
      lng: 73.8786,
      crimeRate: 4.1,
      incidents: 580,
      types: ["theft"],
      safetyScore: 8.2,
    },
    {
      area: "Hadapsar",
      lat: 18.4881,
      lng: 73.9273,
      crimeRate: 5.8,
      incidents: 920,
      types: ["harassment", "theft"],
      safetyScore: 6.8,
    },
    { area: "Kothrud", lat: 18.5276, lng: 73.8119, crimeRate: 5.2, incidents: 750, types: ["theft"], safetyScore: 7.1 },
    {
      area: "Kalyani Nagar",
      lat: 18.5458,
      lng: 73.9155,
      crimeRate: 4.9,
      incidents: 680,
      types: ["theft"],
      safetyScore: 7.3,
    },
  ],
  Hyderabad: [
    {
      area: "Hyderabad Central",
      lat: 17.3833,
      lng: 78.4784,
      crimeRate: 7.2,
      incidents: 1680,
      types: ["theft", "harassment"],
      safetyScore: 4.2,
    },
    {
      area: "Hitech City",
      lat: 17.4409,
      lng: 78.4436,
      crimeRate: 4.3,
      incidents: 620,
      types: ["cyber"],
      safetyScore: 8.4,
    },
    {
      area: "Secunderabad",
      lat: 17.3644,
      lng: 78.4736,
      crimeRate: 6.8,
      incidents: 1420,
      types: ["theft", "harassment"],
      safetyScore: 4.9,
    },
    {
      area: "Banjara Hills",
      lat: 17.3957,
      lng: 78.4592,
      crimeRate: 5.1,
      incidents: 780,
      types: ["theft"],
      safetyScore: 7.4,
    },
    {
      area: "HITEC City",
      lat: 17.4409,
      lng: 78.4436,
      crimeRate: 3.9,
      incidents: 510,
      types: ["cyber"],
      safetyScore: 8.6,
    },
  ],
  Chennai: [
    {
      area: "Chennai Central",
      lat: 13.0827,
      lng: 80.2707,
      crimeRate: 7.1,
      incidents: 1520,
      types: ["theft", "harassment"],
      safetyScore: 4.3,
    },
    {
      area: "Anna Nagar",
      lat: 13.1539,
      lng: 80.2133,
      crimeRate: 4.8,
      incidents: 720,
      types: ["theft"],
      safetyScore: 7.2,
    },
    {
      area: "Velachery",
      lat: 12.9689,
      lng: 80.2241,
      crimeRate: 5.9,
      incidents: 980,
      types: ["harassment", "theft"],
      safetyScore: 6.3,
    },
    {
      area: "Nungambakkam",
      lat: 13.0499,
      lng: 80.2362,
      crimeRate: 6.2,
      incidents: 1050,
      types: ["theft", "cyber"],
      safetyScore: 5.9,
    },
    { area: "Adyar", lat: 13.0044, lng: 80.2436, crimeRate: 5.3, incidents: 850, types: ["theft"], safetyScore: 7.0 },
  ],
}
