// Real India data service with comprehensive resources
export const indiaData = {
  emergencyHelplines: {
    national: [
      {
        name: "Police Emergency",
        number: "100",
        category: "emergency",
        available: "24/7",
        description: "For immediate danger and emergencies",
      },
      {
        name: "National Women Helpline",
        number: "1090",
        category: "women-safety",
        available: "24/7",
        description: "Toll-free support for women in distress",
      },
      {
        name: "Women Helpline (AASRA)",
        number: "9820466726",
        category: "women-support",
        available: "24/7",
        description: "Crisis intervention and counseling",
      },
      {
        name: "iCall Crisis Line",
        number: "9152987821",
        category: "mental-health",
        available: "24/7",
        description: "Mental health and emotional support",
      },
      {
        name: "Vandrevala Foundation",
        number: "9999666555",
        category: "mental-health",
        available: "24/7",
        description: "Crisis counseling and suicide prevention",
      },
      {
        name: "Anti-Human Trafficking",
        number: "1800111555",
        category: "trafficking",
        available: "24/7",
        description: "National human trafficking awareness",
      },
      {
        name: "POCSO Helpline",
        number: "9555000777",
        category: "child-protection",
        available: "24/7",
        description: "Child sexual abuse and exploitation",
      },
      {
        name: "Cyber Crime Helpline",
        number: "1930",
        category: "cybercrime",
        available: "24/7",
        description: "Online harassment and cyber fraud",
      },
      {
        name: "Sexual Harassment at Work",
        number: "1909",
        category: "workplace",
        available: "24/7",
        description: "Workplace sexual harassment complaints",
      },
    ],
    cityWise: {
      delhi: [
        {
          name: "Delhi Women Helpline",
          number: "1091",
          type: "state",
          city: "Delhi",
        },
        {
          name: "Delhi Women Helpline (Alt)",
          number: "011-4141-7343",
          type: "state",
          city: "Delhi",
        },
        {
          name: "Delhi Police - Women Cell",
          number: "011-2330-3999",
          type: "police",
          city: "Delhi",
        },
      ],
      mumbai: [
        {
          name: "Mumbai Women Helpline",
          number: "1090",
          type: "state",
          city: "Mumbai",
        },
        {
          name: "Aasra Helpline",
          number: "9820466726",
          type: "ngo",
          city: "Mumbai",
        },
        {
          name: "Mumbai Police Women Cell",
          number: "22-6169-4438",
          type: "police",
          city: "Mumbai",
        },
      ],
      bangalore: [
        {
          name: "Bangalore Women Helpline",
          number: "1090",
          type: "state",
          city: "Bangalore",
        },
        {
          name: "Bangalore Police Women Cell",
          number: "080-2255-2999",
          type: "police",
          city: "Bangalore",
        },
        {
          name: "Cyber Crime Cell",
          number: "080-4945-6886",
          type: "police",
          city: "Bangalore",
        },
      ],
      kolkata: [
        {
          name: "Kolkata Women Helpline",
          number: "1090",
          type: "state",
          city: "Kolkata",
        },
        {
          name: "Kolkata Police Women Cell",
          number: "033-4040-2000",
          type: "police",
          city: "Kolkata",
        },
      ],
      pune: [
        {
          name: "Pune Women Helpline",
          number: "1090",
          type: "state",
          city: "Pune",
        },
        {
          name: "Pune Police Women Cell",
          number: "020-2622-1313",
          type: "police",
          city: "Pune",
        },
      ],
      hyderabad: [
        {
          name: "Hyderabad Women Helpline",
          number: "1090",
          type: "state",
          city: "Hyderabad",
        },
        {
          name: "Hyderabad Police Women Cell",
          number: "040-2708-5050",
          type: "police",
          city: "Hyderabad",
        },
      ],
      chennai: [
        {
          name: "Chennai Women Helpline",
          number: "1090",
          type: "state",
          city: "Chennai",
        },
        {
          name: "Chennai Police Women Cell",
          number: "044-2459-5050",
          type: "police",
          city: "Chennai",
        },
      ],
      bhopal: [
        {
          name: "Bhopal Women Helpline",
          number: "1090",
          type: "state",
          city: "Bhopal",
        },
        {
          name: "Bhopal Police Women Cell",
          number: "Not Available",
          type: "police",
          city: "Bhopal",
        },
      ],
    },
  },
  importantLaws: [
    {
      name: "Indian Penal Code 354",
      description: "Outraging the modesty of women",
      punishment: "Imprisonment up to 3 years or fine up to 2000 rupees",
      applicable: "All of India",
    },
    {
      name: "Indian Penal Code 376",
      description: "Sexual assault/Rape",
      punishment: "Minimum 7 years to life imprisonment",
      applicable: "All of India",
    },
    {
      name: "Indian Penal Code 509",
      description: "Insult to the modesty of women",
      punishment: "Up to 3 years imprisonment or fine",
      applicable: "All of India",
    },
    {
      name: "Dowry Prohibition Act (1961)",
      description: "Prohibition of dowry in marriages",
      punishment: "Up to 5 years imprisonment and fine",
      applicable: "All of India",
    },
    {
      name: "Protection of Women from Domestic Violence Act (2005)",
      description: "Protection from abuse and violence at home",
      punishment: "Up to 1 year imprisonment or fine",
      applicable: "All of India",
    },
    {
      name: "Sexual Harassment of Women at Workplace Act (2013)",
      description: "POSH Act - Workplace safety",
      punishment: "Various disciplinary actions and legal penalties",
      applicable: "All workplaces in India",
    },
    {
      name: "POCSO Act (2012)",
      description: "Protection of Children from Sexual Offences",
      punishment: "Rigorous imprisonment up to 7 years",
      applicable: "Protection for children",
    },
    {
      name: "Cybercrime Protection",
      description: "IPC 354D - Stalking, online harassment",
      punishment: "Up to 3 years imprisonment",
      applicable: "All of India",
    },
  ],
  crimeSafetyData: {
    highRiskAreas: [
      { city: "Delhi", area: "South Delhi", riskLevel: "moderate", incidents: 450 },
      { city: "Delhi", area: "North Delhi", riskLevel: "high", incidents: 680 },
      { city: "Mumbai", area: "Central Mumbai", riskLevel: "moderate", incidents: 320 },
      { city: "Bangalore", area: "South Bangalore", riskLevel: "low", incidents: 150 },
      { city: "Kolkata", area: "Central Kolkata", riskLevel: "moderate", incidents: 280 },
      { city: "Bhopal", area: "Central Bhopal", riskLevel: "moderate", incidents: 180 },
      { city: "Bhopal", area: "New Market Area", riskLevel: "moderate", incidents: 150 },
      { city: "Bhopal", area: "Upper Lake Area", riskLevel: "moderate", incidents: 120 },
    ],
    safeAreas: [
      { city: "Delhi", area: "Gurgaon", safetyScore: 8.5 },
      { city: "Bangalore", area: "Whitefield", safetyScore: 8.8 },
      { city: "Mumbai", area: "Bandra", safetyScore: 7.9 },
      { city: "Pune", area: "Koregaon Park", safetyScore: 8.2 },
      { city: "Hyderabad", area: "Hitech City", safetyScore: 8.7 },
      { city: "Bhopal", area: "Arera Hills", safetyScore: 8.6 },
      { city: "Bhopal", area: "Raisen Road", safetyScore: 8.3 },
      { city: "Bhopal", area: "Airport Road", safetyScore: 8.4 },
      { city: "Bhopal", area: "Van Vihar", safetyScore: 8.8 },
      { city: "Bhopal", area: "MP Nagar", safetyScore: 8.2 },
    ],
  },
  mentalHealthResources: [
    {
      name: "NMHP Services",
      description: "National Mental Health Programme",
      type: "Government",
      availability: "Pan-India",
    },
    {
      name: "NIMHANS Bangalore",
      description: "National Institute of Mental Health",
      type: "Government",
      phone: "080-2699-5100",
      availability: "Online counselling available",
    },
    {
      name: "Wysa",
      type: "App",
      description: "AI mental health support and therapy",
      availability: "Paid + Free options",
    },
    {
      name: "Sanvello",
      type: "App",
      description: "Mood tracking and therapy support",
      availability: "Paid + Free trial",
    },
    {
      name: "BetterHelp",
      type: "Online",
      description: "Online therapy with licensed therapists",
      availability: "Paid (accepts Indian therapists)",
    },
  ],
  selfDefenseResources: [
    {
      name: "Women's Self Defense Classes",
      description: "Martial arts training in major cities",
      cities: ["Delhi", "Mumbai", "Bangalore", "Pune", "Hyderabad", "Bhopal"],
    },
    {
      name: "Pepper Spray",
      description: "Legal self-defense tool (with permit)",
      availability: "Online and retail stores",
      legalInIndia: true,
    },
    {
      name: "Personal Safety Apps",
      tools: [
        { name: "bSafe", description: "Emergency alert and location sharing" },
        { name: "Circle of 6", description: "Friends support system" },
        { name: "TravelSafe", description: "Travel safety monitoring" },
        { name: "SafetiPin", description: "Safety rating and resources" },
      ],
    },
  ],
}

export const cityLocations = {
  Delhi: [
    { name: "India Gate", lat: 28.6129, lng: 77.2295, type: "landmark", category: "Public Place" },
    { name: "Connaught Place", lat: 28.6305, lng: 77.1896, type: "landmark", category: "Shopping" },
    { name: "New Delhi Railway Station", lat: 28.6431, lng: 77.2197, type: "transport", category: "Transport Hub" },
    { name: "Delhi International Airport", lat: 28.556, lng: 77.1033, type: "transport", category: "Transport Hub" },
    { name: "Indira Gandhi Memorial", lat: 28.5958, lng: 77.2512, type: "landmark", category: "Public Place" },
    { name: "Lodi Garden", lat: 28.5933, lng: 77.2207, type: "park", category: "Park" },
    { name: "Ram Lila Ground", lat: 28.6475, lng: 77.2436, type: "public", category: "Public Ground" },
    { name: "Delhi Police Station - Central", lat: 28.6295, lng: 77.1896, type: "police", category: "Police Station" },
    { name: "Max Hospital Delhi", lat: 28.6139, lng: 77.209, type: "hospital", category: "Hospital" },
    { name: "AIIMS Delhi", lat: 28.5684, lng: 77.2102, type: "hospital", category: "Hospital" },
    { name: "Red Fort", lat: 28.6562, lng: 77.241, type: "landmark", category: "Historical" },
    { name: "Jama Masjid", lat: 28.6505, lng: 77.2308, type: "landmark", category: "Religious" },
    { name: "Chandni Chowk", lat: 28.6505, lng: 77.2308, type: "landmark", category: "Shopping" },
    { name: "Rajiv Chowk Metro", lat: 28.6328, lng: 77.1897, type: "transport", category: "Metro Station" },
    { name: "Safdarjung Hospital", lat: 28.5725, lng: 77.1967, type: "hospital", category: "Hospital" },
    { name: "RML Hospital", lat: 28.6272, lng: 77.2466, type: "hospital", category: "Hospital" },
    { name: "New Delhi Police Station", lat: 28.6431, lng: 77.2197, type: "police", category: "Police Station" },
    { name: "North Avenue Police", lat: 28.625, lng: 77.1897, type: "police", category: "Police Station" },
    { name: "Gurugram Sector 1", lat: 28.4595, lng: 77.0266, type: "landmark", category: "Business District" },
    { name: "Aerocity", lat: 28.5569, lng: 77.0998, type: "landmark", category: "Commercial" },
    { name: "Noida City Centre", lat: 28.5921, lng: 77.3639, type: "landmark", category: "Shopping" },
    { name: "Greater Noida", lat: 28.4744, lng: 77.5661, type: "landmark", category: "Residential" },
    { name: "Dwarka Metro", lat: 28.5855, lng: 77.0457, type: "transport", category: "Metro Station" },
    { name: "Terminal 3 Airport", lat: 28.556, lng: 77.1033, type: "transport", category: "Transport Hub" },
    { name: "Delhi Cantt Railway Station", lat: 28.6441, lng: 77.1504, type: "transport", category: "Railway Station" },
    { name: "ICICI Hospital Delhi", lat: 28.5957, lng: 77.1849, type: "hospital", category: "Hospital" },
    { name: "Fortis Hospital Delhi", lat: 28.5631, lng: 77.2504, type: "hospital", category: "Hospital" },
  ],
  Mumbai: [
    { name: "Gateway of India", lat: 18.9563, lng: 72.8354, type: "landmark", category: "Public Place" },
    { name: "Marine Drive", lat: 18.9432, lng: 72.8289, type: "landmark", category: "Public Place" },
    { name: "Chhatrapati Shivaji Terminus", lat: 18.9337, lng: 72.8326, type: "transport", category: "Transport Hub" },
    { name: "Mumbai International Airport", lat: 19.0904, lng: 72.8656, type: "transport", category: "Transport Hub" },
    { name: "Linking Road", lat: 19.0197, lng: 72.8277, type: "landmark", category: "Shopping" },
    { name: "Worli Sea Face", lat: 19.0176, lng: 72.8194, type: "park", category: "Park" },
    { name: "Mumbai Police Station - Main", lat: 18.9563, lng: 72.8354, type: "police", category: "Police Station" },
    { name: "Breach Candy Hospital", lat: 19.0263, lng: 72.8316, type: "hospital", category: "Hospital" },
    { name: "St. George Hospital", lat: 18.9537, lng: 72.8299, type: "hospital", category: "Hospital" },
    { name: "Taj Mahal Hotel", lat: 18.9563, lng: 72.8354, type: "landmark", category: "Hotel" },
    { name: "Bandra Fort", lat: 19.0436, lng: 72.8254, type: "landmark", category: "Historical" },
    { name: "Fort Railway Station", lat: 18.9532, lng: 72.8341, type: "transport", category: "Railway Station" },
    { name: "Dadar Station", lat: 19.0176, lng: 72.8289, type: "transport", category: "Railway Station" },
    { name: "Hinduja Hospital", lat: 19.0715, lng: 72.8268, type: "hospital", category: "Hospital" },
    { name: "Lilavati Hospital", lat: 19.0197, lng: 72.8277, type: "hospital", category: "Hospital" },
    { name: "Fort Police Station", lat: 18.9537, lng: 72.8341, type: "police", category: "Police Station" },
    { name: "Bandra Police Station", lat: 19.0436, lng: 72.8254, type: "police", category: "Police Station" },
    { name: "Powai Metro", lat: 19.0596, lng: 72.8846, type: "transport", category: "Metro Station" },
    { name: "Andheri Station", lat: 19.1136, lng: 72.8697, type: "transport", category: "Railway Station" },
    { name: "Westend Mall", lat: 19.0197, lng: 72.8277, type: "landmark", category: "Shopping" },
    { name: "BKC Mumbai", lat: 19.0759, lng: 72.8776, type: "landmark", category: "Business District" },
    { name: "Malad Market", lat: 19.1833, lng: 72.8456, type: "landmark", category: "Shopping" },
    { name: "Seawoods Grand Central", lat: 19.056, lng: 73.0206, type: "landmark", category: "Shopping" },
    { name: "Navi Mumbai Hospital", lat: 19.0596, lng: 73.0206, type: "hospital", category: "Hospital" },
  ],
  Bangalore: [
    { name: "Vidhana Soudha", lat: 12.9795, lng: 77.5903, type: "landmark", category: "Public Place" },
    { name: "Cubbon Park", lat: 12.9716, lng: 77.5946, type: "park", category: "Park" },
    { name: "Brigade Road", lat: 12.9716, lng: 77.5946, type: "landmark", category: "Shopping" },
    {
      name: "Kempegowda International Airport",
      lat: 13.1939,
      lng: 77.7064,
      type: "transport",
      category: "Transport Hub",
    },
    {
      name: "Bangalore City Railway Station",
      lat: 12.9756,
      lng: 77.6411,
      type: "transport",
      category: "Transport Hub",
    },
    { name: "Bangalore Central Police", lat: 12.9716, lng: 77.5946, type: "police", category: "Police Station" },
    { name: "Apollo Hospital Bangalore", lat: 13.0359, lng: 77.6245, type: "hospital", category: "Hospital" },
    { name: "St. Martha's Hospital", lat: 13.0359, lng: 77.5903, type: "hospital", category: "Hospital" },
    { name: "Nandi Hills", lat: 13.3623, lng: 77.471, type: "landmark", category: "Hill Station" },
    { name: "Lal Bagh", lat: 12.9352, lng: 77.5904, type: "park", category: "Park" },
    { name: "Bangla Sahib Gurudwara", lat: 13.0359, lng: 77.5903, type: "landmark", category: "Religious" },
    { name: "Yelahanka Station", lat: 13.0794, lng: 77.5913, type: "transport", category: "Railway Station" },
    { name: "Whitefield Metro", lat: 13.0259, lng: 77.6245, type: "transport", category: "Metro Station" },
    { name: "Fortis Hospital", lat: 13.0359, lng: 77.5903, type: "hospital", category: "Hospital" },
    { name: "Manipal Hospital", lat: 12.9716, lng: 77.5946, type: "hospital", category: "Hospital" },
    { name: "Whitefield Police Station", lat: 13.0259, lng: 77.6245, type: "police", category: "Police Station" },
    { name: "Koramangala", lat: 12.9352, lng: 77.6245, type: "landmark", category: "Commercial" },
    { name: "Indiranagar", lat: 13.0359, lng: 77.6245, type: "landmark", category: "Residential" },
    { name: "MG Road Metro", lat: 12.9352, lng: 77.5904, type: "transport", category: "Metro Station" },
    { name: "Baiyappanahalli Station", lat: 12.9657, lng: 77.6518, type: "transport", category: "Railway Station" },
    { name: "Mantri Square Mall", lat: 12.9716, lng: 77.5946, type: "landmark", category: "Shopping" },
    { name: "Vijayanagar Market", lat: 13.0359, lng: 77.5903, type: "landmark", category: "Shopping" },
  ],
  Kolkata: [
    { name: "Victoria Memorial", lat: 22.5448, lng: 88.3426, type: "landmark", category: "Public Place" },
    { name: "Howrah Bridge", lat: 22.5731, lng: 88.3639, type: "landmark", category: "Public Place" },
    { name: "Howrah Railway Station", lat: 22.5898, lng: 88.2775, type: "transport", category: "Transport Hub" },
    {
      name: "Netaji Subhas Chandra Bose International Airport",
      lat: 22.6542,
      lng: 88.4467,
      type: "transport",
      category: "Transport Hub",
    },
    { name: "Kolkata Police - Main Office", lat: 22.5726, lng: 88.3639, type: "police", category: "Police Station" },
    { name: "AMRI Hospital", lat: 22.4885, lng: 88.3763, type: "hospital", category: "Hospital" },
    { name: "Indian Museum", lat: 22.5448, lng: 88.3426, type: "landmark", category: "Museum" },
    { name: "St. Paul's Cathedral", lat: 22.5448, lng: 88.3426, type: "landmark", category: "Religious" },
    { name: "Rabindra Sarovar", lat: 22.5167, lng: 88.3667, type: "park", category: "Park" },
    { name: "Sealdah Railway Station", lat: 22.5629, lng: 88.3646, type: "transport", category: "Railway Station" },
    { name: "Kolkata Metro - Esplanade", lat: 22.5726, lng: 88.3639, type: "transport", category: "Metro Station" },
    { name: "SSKM Hospital", lat: 22.5448, lng: 88.3426, type: "hospital", category: "Hospital" },
    { name: "NRS Medical College", lat: 22.5167, lng: 88.3667, type: "hospital", category: "Hospital" },
    { name: "AJC Bose Road Police", lat: 22.5726, lng: 88.3639, type: "police", category: "Police Station" },
    { name: "Alipore Zoo", lat: 22.5448, lng: 88.3426, type: "landmark", category: "Public Place" },
    { name: "Salt Lake Metro", lat: 22.5571, lng: 88.3748, type: "transport", category: "Metro Station" },
    { name: "New Town Kolkata", lat: 22.5733, lng: 88.4496, type: "landmark", category: "Residential" },
    { name: "AJC Bose Road", lat: 22.5726, lng: 88.3639, type: "landmark", category: "Commercial" },
  ],
  Pune: [
    { name: "Aga Khan Palace", lat: 18.5297, lng: 73.8786, type: "landmark", category: "Public Place" },
    { name: "Koregaon Park", lat: 18.5333, lng: 73.8667, type: "park", category: "Park" },
    { name: "Pune Railway Station", lat: 18.5241, lng: 73.8474, type: "transport", category: "Transport Hub" },
    { name: "Pune Airport", lat: 18.5799, lng: 73.9197, type: "transport", category: "Transport Hub" },
    { name: "Pune Police Headquarters", lat: 18.5197, lng: 73.8567, type: "police", category: "Police Station" },
    { name: "Ruby Hall Clinic", lat: 18.5299, lng: 73.9272, type: "hospital", category: "Hospital" },
    { name: "Shaniwar Wada", lat: 18.5204, lng: 73.8567, type: "landmark", category: "Historical" },
    { name: "Osho Ashram", lat: 18.5333, lng: 73.8667, type: "landmark", category: "Spiritual" },
    { name: "Raja Dinkar Kelkar Museum", lat: 18.5197, lng: 73.8567, type: "landmark", category: "Museum" },
    { name: "Pune Junction Station", lat: 18.5241, lng: 73.8474, type: "transport", category: "Railway Station" },
    { name: "Hadapsar Bus Station", lat: 18.5109, lng: 73.9272, type: "transport", category: "Bus Station" },
    { name: "Deenanath Mangeshkar Hospital", lat: 18.5299, lng: 73.9272, type: "hospital", category: "Hospital" },
    { name: "Inlaks Hospital", lat: 18.5197, lng: 73.8567, type: "hospital", category: "Hospital" },
    { name: "Camp Police Station", lat: 18.5204, lng: 73.8567, type: "police", category: "Police Station" },
    { name: "Viman Nagar", lat: 18.5652, lng: 73.9153, type: "landmark", category: "Residential" },
    { name: "Hinjewadi", lat: 18.5961, lng: 73.8269, type: "landmark", category: "IT Park" },
    { name: "Phoenix Market City", lat: 18.5333, lng: 73.8667, type: "landmark", category: "Shopping" },
    { name: "Aundh", lat: 18.5574, lng: 73.8075, type: "landmark", category: "Residential" },
  ],
  Hyderabad: [
    { name: "Charminar", lat: 17.3607, lng: 78.4594, type: "landmark", category: "Public Place" },
    {
      name: "Hyderabad International Airport",
      lat: 17.3898,
      lng: 78.4389,
      type: "transport",
      category: "Transport Hub",
    },
    { name: "Hyderabad Railway Station", lat: 17.3644, lng: 78.4736, type: "transport", category: "Transport Hub" },
    { name: "Hyderabad Police - Main Office", lat: 17.3833, lng: 78.4784, type: "police", category: "Police Station" },
    { name: "Apollo Hospital Hyderabad", lat: 17.4239, lng: 78.4436, type: "hospital", category: "Hospital" },
    { name: "Mecca Masjid", lat: 17.3607, lng: 78.4594, type: "landmark", category: "Religious" },
    { name: "Golkonda Fort", lat: 17.3639, lng: 78.4071, type: "landmark", category: "Historical" },
    { name: "NTR Gardens", lat: 17.3878, lng: 78.4705, type: "park", category: "Park" },
    { name: "Hyderabad Central Station", lat: 17.3644, lng: 78.4736, type: "transport", category: "Railway Station" },
    { name: "HITEC City Metro", lat: 17.4514, lng: 78.3829, type: "transport", category: "Metro Station" },
    { name: "CARE Hospitals", lat: 17.4239, lng: 78.4436, type: "hospital", category: "Hospital" },
    { name: "Yashoda Hospital", lat: 17.3833, lng: 78.4784, type: "hospital", category: "Hospital" },
    { name: "Abids Police Station", lat: 17.3607, lng: 78.4594, type: "police", category: "Police Station" },
    { name: "Secunderabad Station", lat: 17.3629, lng: 78.5011, type: "transport", category: "Railway Station" },
    { name: "Ameerpet Metro", lat: 17.3898, lng: 78.4389, type: "transport", category: "Metro Station" },
    { name: "Banjara Hills", lat: 17.3928, lng: 78.4494, type: "landmark", category: "Residential" },
    { name: "Jubilee Hills", lat: 17.3947, lng: 78.4417, type: "landmark", category: "Residential" },
  ],
  Chennai: [
    { name: "Marina Beach", lat: 13.0499, lng: 80.2822, type: "landmark", category: "Public Place" },
    {
      name: "Chennai Central Railway Station",
      lat: 13.0847,
      lng: 80.2744,
      type: "transport",
      category: "Transport Hub",
    },
    { name: "Chennai International Airport", lat: 12.9942, lng: 80.1709, type: "transport", category: "Transport Hub" },
    {
      name: "Chennai Police Commissioner Office",
      lat: 13.0827,
      lng: 80.2707,
      type: "police",
      category: "Police Station",
    },
    { name: "Apollo Hospital Chennai", lat: 13.0499, lng: 80.2822, type: "hospital", category: "Hospital" },
    { name: "Kapaleeshwarar Temple", lat: 13.0499, lng: 80.2822, type: "landmark", category: "Religious" },
    { name: "Fort St. George", lat: 13.0847, lng: 80.2744, type: "landmark", category: "Historical" },
    { name: "Abirami Temple", lat: 12.9716, lng: 80.2822, type: "landmark", category: "Religious" },
    { name: "Chennai Egmore Station", lat: 13.0827, lng: 80.2707, type: "transport", category: "Railway Station" },
    { name: "Chennai Central Metro", lat: 13.0847, lng: 80.2744, type: "transport", category: "Metro Station" },
    { name: "Dr. Rela Institute", lat: 13.0499, lng: 80.2822, type: "hospital", category: "Hospital" },
    { name: "Fortis Malar Hospital", lat: 13.0827, lng: 80.2707, type: "hospital", category: "Hospital" },
    { name: "Teynampet Police Station", lat: 13.0499, lng: 80.2822, type: "police", category: "Police Station" },
    { name: "T. Nagar Metro", lat: 13.0359, lng: 80.2245, type: "transport", category: "Metro Station" },
    { name: "Kodambakkam", lat: 13.0045, lng: 80.2245, type: "landmark", category: "Commercial" },
    { name: "Guindy National Park", lat: 13.0089, lng: 80.2245, type: "park", category: "Park" },
  ],
  Gurgaon: [
    { name: "Cyber Hub", lat: 28.4595, lng: 77.0266, type: "landmark", category: "Shopping" },
    { name: "Gurgaon Railway Station", lat: 28.4595, lng: 77.0266, type: "transport", category: "Transport Hub" },
    { name: "Gurgaon Police Headquarters", lat: 28.4595, lng: 77.0266, type: "police", category: "Police Station" },
    { name: "Max Hospital Gurgaon", lat: 28.4595, lng: 77.0266, type: "hospital", category: "Hospital" },
    { name: "Kingdom of Dreams", lat: 28.4595, lng: 77.0266, type: "landmark", category: "Entertainment" },
    { name: "Golf Course Road", lat: 28.4489, lng: 77.0389, type: "landmark", category: "Shopping" },
    { name: "DLF Cyber Hub", lat: 28.4595, lng: 77.0266, type: "landmark", category: "Commercial" },
    { name: "Gurgaon Central Station", lat: 28.4589, lng: 77.0266, type: "transport", category: "Railway Station" },
    { name: "Indira Gandhi International", lat: 28.5562, lng: 77.1033, type: "transport", category: "Airport" },
    { name: "Medanta Hospital", lat: 28.4595, lng: 77.0266, type: "hospital", category: "Hospital" },
    { name: "Apollo Hospital Gurgaon", lat: 28.4595, lng: 77.0266, type: "hospital", category: "Hospital" },
    { name: "Gurgaon City Center Police", lat: 28.4595, lng: 77.0266, type: "police", category: "Police Station" },
  ],
  Bhopal: [
    { name: "Taj-ul-Masajid", lat: 23.1855, lng: 77.4149, type: "landmark", category: "Religious" },
    { name: "Van Vihar National Park", lat: 23.2093, lng: 77.4849, type: "park", category: "Park" },
    { name: "Upper Lake", lat: 23.1673, lng: 77.4169, type: "landmark", category: "Public Place" },
    { name: "Bhopal Railway Station", lat: 23.1833, lng: 77.4317, type: "transport", category: "Transport Hub" },
    {
      name: "Raja Bhoj International Airport",
      lat: 23.2821,
      lng: 77.3739,
      type: "transport",
      category: "Transport Hub",
    },
    { name: "Arera Hills Market", lat: 23.2093, lng: 77.4849, type: "landmark", category: "Shopping" },
    { name: "New Market", lat: 23.1855, lng: 77.4149, type: "landmark", category: "Shopping" },
    { name: "Bhopal Central Police", lat: 23.1833, lng: 77.4317, type: "police", category: "Police Station" },
    { name: "Arera Hills Police Station", lat: 23.2093, lng: 77.4849, type: "police", category: "Police Station" },
    { name: "Raisen Road Police", lat: 23.1673, lng: 77.4169, type: "police", category: "Police Station" },
    { name: "Apex Hospital Bhopal", lat: 23.2093, lng: 77.4849, type: "hospital", category: "Hospital" },
    { name: "Chirayu Hospital", lat: 23.1833, lng: 77.4317, type: "hospital", category: "Hospital" },
    { name: "Bansal Hospital", lat: 23.1673, lng: 77.4169, type: "hospital", category: "Hospital" },
    { name: "Saket Hospital", lat: 23.2093, lng: 77.4849, type: "hospital", category: "Hospital" },
    { name: "Lower Lake", lat: 23.1495, lng: 77.3849, type: "landmark", category: "Public Place" },
    {
      name: "Indira Gandhi Rashtriya Manav Sangrahalaya",
      lat: 23.1909,
      lng: 77.4282,
      type: "landmark",
      category: "Museum",
    },
    { name: "Habibganj Bus Station", lat: 23.1833, lng: 77.4317, type: "transport", category: "Bus Station" },
    { name: "MP Nagar Market", lat: 23.1909, lng: 77.4282, type: "landmark", category: "Shopping" },
  ],
}

export const crimeAreasData = {
  Bhopal: [
    {
      name: "Central Bhopal",
      lat: 23.1855,
      lng: 77.4149,
      riskLevel: "moderate",
      incidents: 180,
      safetyScore: 7.2,
      crimeTypes: ["petty theft", "street harassment"],
    },
    {
      name: "New Market Area",
      lat: 23.1855,
      lng: 77.4149,
      riskLevel: "moderate",
      incidents: 150,
      safetyScore: 7.4,
      crimeTypes: ["crowded areas", "pickpocketing"],
    },
    {
      name: "Arera Hills",
      lat: 23.2093,
      lng: 77.4849,
      riskLevel: "low",
      incidents: 45,
      safetyScore: 8.6,
      crimeTypes: [],
    },
    {
      name: "Raisen Road",
      lat: 23.1673,
      lng: 77.4169,
      riskLevel: "low",
      incidents: 60,
      safetyScore: 8.3,
      crimeTypes: [],
    },
    {
      name: "Airport Road",
      lat: 23.2821,
      lng: 77.3739,
      riskLevel: "low",
      incidents: 50,
      safetyScore: 8.4,
      crimeTypes: [],
    },
    {
      name: "Van Vihar",
      lat: 23.2093,
      lng: 77.4849,
      riskLevel: "low",
      incidents: 30,
      safetyScore: 8.8,
      crimeTypes: [],
    },
    {
      name: "Upper Lake Area",
      lat: 23.1673,
      lng: 77.4169,
      riskLevel: "moderate",
      incidents: 120,
      safetyScore: 7.5,
      crimeTypes: ["street crime"],
    },
    { name: "MP Nagar", lat: 23.1909, lng: 77.4282, riskLevel: "low", incidents: 70, safetyScore: 8.2, crimeTypes: [] },
  ],
  Delhi: [
    {
      name: "Central Delhi",
      lat: 28.6295,
      lng: 77.1896,
      riskLevel: "high",
      incidents: 680,
      safetyScore: 5.8,
      crimeTypes: ["street crime", "harassment", "assault"],
    },
    {
      name: "North Delhi",
      lat: 28.6475,
      lng: 77.2436,
      riskLevel: "high",
      incidents: 650,
      safetyScore: 6.2,
      crimeTypes: ["robbery", "harassment"],
    },
    {
      name: "South Delhi",
      lat: 28.5933,
      lng: 77.2207,
      riskLevel: "moderate",
      incidents: 450,
      safetyScore: 7.1,
      crimeTypes: ["petty theft"],
    },
    {
      name: "Gurgaon Sector 1",
      lat: 28.4595,
      lng: 77.0266,
      riskLevel: "low",
      incidents: 120,
      safetyScore: 8.5,
      crimeTypes: [],
    },
    { name: "Noida", lat: 28.5921, lng: 77.3639, riskLevel: "low", incidents: 100, safetyScore: 8.3, crimeTypes: [] },
    {
      name: "Dwarka",
      lat: 28.5855,
      lng: 77.0457,
      riskLevel: "moderate",
      incidents: 200,
      safetyScore: 7.6,
      crimeTypes: [],
    },
    { name: "Aerocity", lat: 28.5569, lng: 77.0998, riskLevel: "low", incidents: 80, safetyScore: 8.7, crimeTypes: [] },
  ],
  Mumbai: [
    {
      name: "Central Mumbai",
      lat: 18.9563,
      lng: 72.8354,
      riskLevel: "moderate",
      incidents: 320,
      safetyScore: 7.3,
      crimeTypes: ["pickpocketing"],
    },
    {
      name: "South Mumbai",
      lat: 19.0197,
      lng: 72.8277,
      riskLevel: "low",
      incidents: 150,
      safetyScore: 8.1,
      crimeTypes: [],
    },
    { name: "Bandra", lat: 19.0436, lng: 72.8254, riskLevel: "low", incidents: 140, safetyScore: 8.2, crimeTypes: [] },
    {
      name: "Andheri",
      lat: 19.1136,
      lng: 72.8697,
      riskLevel: "moderate",
      incidents: 280,
      safetyScore: 7.4,
      crimeTypes: ["street crime"],
    },
    {
      name: "BKC Area",
      lat: 19.0759,
      lng: 72.8776,
      riskLevel: "low",
      incidents: 100,
      safetyScore: 8.5,
      crimeTypes: [],
    },
    {
      name: "Malad",
      lat: 19.1833,
      lng: 72.8456,
      riskLevel: "moderate",
      incidents: 220,
      safetyScore: 7.6,
      crimeTypes: [],
    },
  ],
  Bangalore: [
    {
      name: "Central Bangalore",
      lat: 12.9716,
      lng: 77.5946,
      riskLevel: "low",
      incidents: 200,
      safetyScore: 8.2,
      crimeTypes: ["petty theft"],
    },
    {
      name: "Whitefield",
      lat: 13.0259,
      lng: 77.6245,
      riskLevel: "low",
      incidents: 120,
      safetyScore: 8.6,
      crimeTypes: [],
    },
    {
      name: "Indiranagar",
      lat: 13.0359,
      lng: 77.6245,
      riskLevel: "low",
      incidents: 110,
      safetyScore: 8.4,
      crimeTypes: [],
    },
    {
      name: "Koramangala",
      lat: 12.9352,
      lng: 77.6245,
      riskLevel: "low",
      incidents: 130,
      safetyScore: 8.3,
      crimeTypes: [],
    },
  ],
  Kolkata: [
    {
      name: "Central Kolkata",
      lat: 22.5726,
      lng: 88.3639,
      riskLevel: "moderate",
      incidents: 280,
      safetyScore: 7.4,
      crimeTypes: ["street crime"],
    },
    {
      name: "Salt Lake",
      lat: 22.5571,
      lng: 88.3748,
      riskLevel: "low",
      incidents: 100,
      safetyScore: 8.5,
      crimeTypes: [],
    },
  ],
  Pune: [
    {
      name: "Central Pune",
      lat: 18.5204,
      lng: 73.8567,
      riskLevel: "low",
      incidents: 180,
      safetyScore: 8.0,
      crimeTypes: ["petty theft"],
    },
    {
      name: "Koregaon Park",
      lat: 18.5333,
      lng: 73.8667,
      riskLevel: "low",
      incidents: 100,
      safetyScore: 8.5,
      crimeTypes: [],
    },
    {
      name: "Viman Nagar",
      lat: 18.5652,
      lng: 73.9153,
      riskLevel: "low",
      incidents: 110,
      safetyScore: 8.3,
      crimeTypes: [],
    },
  ],
  Hyderabad: [
    {
      name: "Central Hyderabad",
      lat: 17.3607,
      lng: 78.4594,
      riskLevel: "low",
      incidents: 150,
      safetyScore: 8.2,
      crimeTypes: [],
    },
    {
      name: "HITEC City",
      lat: 17.4514,
      lng: 78.3829,
      riskLevel: "low",
      incidents: 100,
      safetyScore: 8.6,
      crimeTypes: [],
    },
  ],
  Chennai: [
    {
      name: "Central Chennai",
      lat: 13.0827,
      lng: 80.2707,
      riskLevel: "low",
      incidents: 140,
      safetyScore: 8.1,
      crimeTypes: [],
    },
    {
      name: "T. Nagar",
      lat: 13.0359,
      lng: 80.2245,
      riskLevel: "low",
      incidents: 120,
      safetyScore: 8.3,
      crimeTypes: [],
    },
  ],
}
